### ISSUE TITLE
The title and the composer name aren't printed anymore

### ISSUE THREAD

**Issue by rbelouin** [music-suite/music-score#341]
Hi!

[This line](https://github.com/music-suite/music-score/blob/master/src/Music/Score/Export/Lilypond.hs#L594) is explicitly commented. Is there a good reason for hiding the title and the composer name when exporting a PDF?

It causes a lack of consistency: the "bug" does not occur when exporting a XML file.

**Comment by hanshoglund** [comment]
This repo has been merged into: https://github.com/music-suite/music-suite. Please open any new issues there!

Closing :)
